# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WxUk6sMvrq7nR_v2R0xgiz-gyBVFajDB
"""

print("¡Hola mundo!")

nota1 = float(input("Nota 1: "))
nota2 = float(input("Nota 2: "))
nota3 = float(input("Nota 3: "))
promedio = (nota1+nota2+nota3)/3
print("promedio", promedio)

nombre = input ('nombre: ')
edad = input ('edad: ')
materia = input ('materia: ')

print('nombre: ' + nombre)
print('edad: ' + edad)
print('aprendiendo: ' + materia)

numero1 = 10
numero2 = 20

suma = numero1+numero2
print("suma", suma)
resta = numero1-numero2
print("resta", resta)
multi = numero1*numero2
print("multi", multi)
divi = numero1/numero2
print("divi", divi)

nombre = input("Nombre: ")
edad = int(input("Edad: "))

print("----------------------")
print("Nombre:", nombre)
print("Edad:", edad)

if edad >= 18:
    print("Puede votar")
else:
    print("Todavía no puede votar")

import pandas as pd

# DATOS DE ESTUDIANTES

estudiantes = {
    "ID": [1, 2, 3, 4, 5, 6],

    "Nombre": [
        "Ana",
        "Carlos",
        "Maria",
        "Jose",
        "Laura",
        "Pedro"
    ],

    "Edad": [20, 22, 19, 25, 21, 23],

    "Curso": [
        "Python",
        "Python",
        "SQL",
        "SQL",
        "Python",
        "SQL"
    ],

    "Nota": [95, 78, 88, 65, 92, 55],

    "Asistencia": [90, 85, 95, 70, 98, 60]
}

# DATOS DE ANIMALES

animales = {
    "ID": [
        1, 2, 3, 4, 5,
        6, 7, 8, 9, 10,
        11, 12, 13, 14, 15,
        16, 17, 18, 19, 20
    ],

    "Animal": [
        "León", "Tigre", "Elefante", "Jirafa", "Cebra",
        "Mono", "Gorila", "Oso", "Panda", "Canguro",
        "Hipopótamo", "Rinoceronte", "Cocodrilo", "Serpiente",
        "Águila", "Pingüino", "Flamenco", "Tortuga",
        "Lobo", "Zorro"
    ],

    "Especie": [
        "Panthera leo",
        "Panthera tigris",
        "Loxodonta africana",
        "Giraffa camelopardalis",
        "Equus quagga",
        "Macaca",
        "Gorilla gorilla",
        "Ursus arctos",
        "Ailuropoda melanoleuca",
        "Macropus",
        "Hippopotamus amphibius",
        "Ceratotherium simum",
        "Crocodylus",
        "Python",
        "Aquila",
        "Spheniscidae",
        "Phoenicopterus",
        "Testudines",
        "Canis lupus",
        "Vulpes vulpes"
    ],

    "Edad": [
        8, 6, 15, 10, 7,
        5, 12, 9, 4, 6,
        14, 18, 11, 7, 13,
        5, 8, 20, 6, 4
    ],

    "Genero": [
        "Macho", "Hembra", "Hembra", "Macho", "Hembra",
        "Macho", "Hembra", "Macho", "Hembra", "Macho",
        "Hembra", "Macho", "Macho", "Hembra", "Macho",
        "Hembra", "Hembra", "Macho", "Macho", "Hembra"
    ],

    "Habitat": [
        "Sabana", "Selva", "Sabana", "Sabana", "Sabana",
        "Selva", "Selva", "Bosque", "Bosque", "Pradera",
        "Río", "Sabana", "Río", "Selva", "Montaña",
        "Antártida", "Humedal", "Río", "Bosque", "Bosque"
    ],

    "Alimentacion": [
        "Carnívoro", "Carnívoro", "Herbívoro", "Herbívoro",
        "Herbívoro", "Omnívoro", "Herbívoro", "Omnívoro",
        "Herbívoro", "Herbívoro", "Herbívoro", "Herbívoro",
        "Carnívoro", "Carnívoro", "Carnívoro", "Carnívoro",
        "Herbívoro", "Herbívoro", "Carnívoro", "Omnívoro"
    ]
}

# Crear DataFrame
df_estudiantes = pd.DataFrame(estudiantes)
df_animales = pd.DataFrame(animales)

while True:
    print("\n===== MENÚ PRINCIPAL =====")
    print("1. Saludar")
    print("2. Mostrar Nombre.")
    print("3. Sumar Numeros.")
    print("4. Mostrar Promedio.")
    print("5. Aplicar Analisis")
    print("6. Buscar Animal.")
    print("7. Salir")

    opcion = input("Seleccione una opcion :")

    if opcion == "1":
     print("¡Hola! Bienvenido al programa.")

    elif opcion == "2":
        nombre = input("Digite su nombre: ")
        print("Hola", nombre)

    elif opcion == "3":
        num1 = float(input("Digite el primer numero: "))
        num2 = float(input("Digite el segundo numero: "))
        suma = num1 + num2
        print("La suma es:", suma)

    elif opcion == "4":
        nota1 = float(input("Digite la primera nota: "))
        nota2 = float(input("Digite la segunda nota: "))
        nota3 = float(input("Digite la tercera nota: "))
        promedio = (nota1 + nota2 + nota3) / 3
        print("El promedio es:", promedio)

    elif opcion == "5":
     while True:
        print("\n===== SUBMENÚ ANÁLISIS =====")
        print("1. Mostrar Tabla")
        print("2. Mostrar Información")
        print("3. Mostrar Estadística")
        print("4. Buscar Estudiante")
        print("5. Mostrar estudiantes aprobados")
        print("6. Mostrar estudiantes reprobados")
        print("7. Promedio de notas")
        print("8. Promedio por curso")
        print("9. Regresar")

        opcion2 = input("Seleccione una opción: ")

        if opcion2 == "1":
            print("Mostrar Tabla")

        elif opcion2 == "2":
            print("Mostrar Información")

        elif opcion2 == "3":
            print("Mostrar Estadística")

        elif opcion2 == "4":
            nombre = input("Digite el nombre del estudiante: ")
            print("Buscando estudiante:", nombre)

        elif opcion2 == "5":
            print("Mostrando estudiantes aprobados")

        elif opcion2 == "6":
            print("Mostrando estudiantes reprobados")

        elif opcion2 == "7":
            print("Mostrando promedio de notas")

        elif opcion2 == "8":
            print("Mostrando promedio por curso")

        elif opcion2 == "9":
            print("Regresando al menú principal...")
            break

        else:
            print("Opción no válida.")

    elif opcion == "6":

       while True:

        print("\n===== SUBMENÚ DE ANIMALES =====")
        print("1. Mostrar tabla de animales")
        print("2. Buscar animal")
        print("3. Regresar")

        opcion_animal = input("Seleccione una opción: ")

        if opcion_animal == "1":
            print("\nTABLA DE ANIMALES")
            print(df_animales.to_string(index=False))

        elif opcion_animal == "2":
            print("\nBuscando")

        elif opcion_animal == "3":
            print("Regresando al menú principal...")
            break

        else:
            print("Opción no válida.")

    elif opcion == "7":
        print("Gracias por utilizar el programa.")
        break


    else:
        print("Opción no válida. Intente nuevamente.")