CREATE DATABASE Colegio;
GO

USE Colegio;
GO

-- TABLA DOCENTE

CREATE TABLE Docente (
    Ced VARCHAR(20) NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Materia VARCHAR(100)
);

-- TABLA ASIGNATURA

CREATE TABLE Asignatura (
    CodAsignatura INT IDENTITY(1,1) PRIMARY KEY,
    NombreAsignatura VARCHAR(100) NOT NULL,
    Ced VARCHAR(20) NOT NULL,

    CONSTRAINT FK_Asignatura_Docente -- REFERENCIA RELACION ENTRE TABLAS
        FOREIGN KEY (Ced)-- INDICA QUE ES LA LLAVE FORANEA
        REFERENCES Docente(Ced) -- EL VALOR DEBE EXISTIR EN LA TABLA DOCENTE
);

-- TABLA ALUMNO

CREATE TABLE Alumno (
    DNI VARCHAR(20) NOT NULL PRIMARY KEY,
    Nombre VARCHAR(50) NOT NULL,
    Apellido VARCHAR(50) NOT NULL,
    Domicilio VARCHAR(150)
);

-- TABLA CALIFICACION

CREATE TABLE Calificacion (
    IdCalificacion INT IDENTITY(1,1) PRIMARY KEY,
    CodAsignatura INT NOT NULL,
    DNI VARCHAR(20) NOT NULL,
    Nota DECIMAL(4,2) NOT NULL,

    CONSTRAINT FK_Calificacion_Asignatura --REFERENCIA RELACION ENTRE TABLAS
        FOREIGN KEY (CodAsignatura)--INDICA QUE ES LA LLAVE FORANEA
        REFERENCES Asignatura(CodAsignatura),-- EL VALOR DEBE EXISTIR EN LA TABLA ASIGNATURA

    CONSTRAINT FK_Calificacion_Alumno --REFERENCIA RELACION ENTRE TABLAS
        FOREIGN KEY (DNI)--INDICA QUE ES LA LLAVE FORANEA
        REFERENCES Alumno(DNI)-- EL VALOR DEBE EXISTIR EN LA TABLA ALUMNO
);